const handleError = setError => {
  setError('Oops, some error occurred. Please, try again later.');
};

export default handleError;
